/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Bookshelf.glb -t 
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube007: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube014_1: THREE.Mesh;
    Cube017_1: THREE.Mesh;
    Cube017_2: THREE.Mesh;
    Cube017_3: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube021_1: THREE.Mesh;
    Cube021_2: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cube023_1: THREE.Mesh;
    Cube023_2: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube010_1: THREE.Mesh;
    Cube010_2: THREE.Mesh;
    Cube010_3: THREE.Mesh;
  };
  materials: {
    table: THREE.MeshStandardMaterial;
    book2: THREE.MeshStandardMaterial;
    book3: THREE.MeshStandardMaterial;
    book1: THREE.MeshStandardMaterial;
    ["book1.001"]: THREE.MeshStandardMaterial;
    ["book2.001"]: THREE.MeshStandardMaterial;
    ["book3.001"]: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function Bookshelf(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/room/Bookshelf.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials.table}
        position={[-1.259, 3.12, -2.857]}
        rotation={[Math.PI, -Math.PI / 2, 0]}
        scale={[-0.339, -0.604, -1.885]}
      />
      <group position={[-2.895, 3.11, -2.857]} scale={[0.03, 0.175, 0.175]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials.book2} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials.book3} />
      </group>
      <group position={[-2.926, 3.503, -2.857]} scale={[0.03, 0.166, 0.175]}>
        <mesh geometry={nodes.Cube017_1.geometry} material={materials.book1} />
        <mesh geometry={nodes.Cube017_2.geometry} material={materials.book2} />
        <mesh geometry={nodes.Cube017_3.geometry} material={materials.book3} />
      </group>
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials.book3}
        position={[-1.853, 2.606, -2.857]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.03, 0.166, 0.175]}
      />
      <group position={[-2.9, 2.739, -2.857]} scale={[0.03, 0.175, 0.175]}>
        <mesh geometry={nodes.Cube021_1.geometry} material={materials.book2} />
        <mesh geometry={nodes.Cube021_2.geometry} material={materials.book1} />
      </group>
      <group position={[-2.467, 3.1, -2.857]} scale={[0.03, 0.175, 0.175]}>
        <mesh geometry={nodes.Cube023.geometry} material={materials.book1} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials.book3} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials.book2} />
      </group>
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials.book2}
        position={[-1.839, 2.664, -2.882]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.03, 0.166, 0.175]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials.book3}
        position={[-1.411, 2.965, -2.857]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.03, 0.166, 0.175]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials.book1}
        position={[-1.411, 3.023, -2.882]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.03, 0.166, 0.175]}
      />
      <group position={[-2.926, 3.503, -2.857]} scale={[0.03, 0.166, 0.175]}>
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials["book1.001"]}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials["book2.001"]}
        />
        <mesh
          geometry={nodes.Cube010_3.geometry}
          material={materials["book3.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/room/Bookshelf.glb");
