/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Calendar.glb -t 
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Calendar_Base: THREE.Mesh;
    Calendar_Page: THREE.Mesh;
    Calendar_Spine: THREE.Mesh;
  };
  materials: {
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function Calendar(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/room/Calendar.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Calendar_Base.geometry}
        material={materials["Material.008"]}
        position={[-0.116, 1.894, -3.193]}
        scale={[0.4, 0.5, 0.01]}
      />
      <mesh
        geometry={nodes.Calendar_Page.geometry}
        material={materials["Material.009"]}
        position={[-0.117, 1.647, -3.181]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.39, 1, 0.24]}
      />
      <mesh
        geometry={nodes.Calendar_Spine.geometry}
        material={materials["Material.005"]}
        position={[-0.117, 1.893, -3.187]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.01, 0.4, 0.01]}
      />
    </group>
  );
}

useGLTF.preload("/room/Calendar.glb");
