/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 NoticeBoard.glb -t 
*/

import { useGLTF } from "@react-three/drei";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    NoticeBoardWood: THREE.Mesh;
    NoticeBoardFrame: THREE.Mesh;
    Poster1: THREE.Mesh;
    Poster2: THREE.Mesh;
    Poster3: THREE.Mesh;
    Poster4: THREE.Mesh;
  };
  materials: {
    ["Material.012"]: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function NoticeBoard(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/room/NoticeBoard.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.NoticeBoardWood.geometry}
        material={materials["Material.012"]}
        position={[1.884, 2.44, -3.166]}
        scale={[0.9, 0.9, 0.03]}
      />
      <mesh
        geometry={nodes.NoticeBoardFrame.geometry}
        material={materials["Material.013"]}
        position={[1.884, 2.44, -3.147]}
        scale={[1, 1, 0.05]}
      />
      <mesh
        geometry={nodes.Poster1.geometry}
        material={nodes.Poster1.material}
        position={[1.297, 2.974, -3.089]}
        rotation={[Math.PI / 2, -0.087, 0]}
        scale={[0.2, 1, 0.283]}
      />
      <mesh
        geometry={nodes.Poster2.geometry}
        material={nodes.Poster2.material}
        position={[1.744, 2.974, -3.089]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.2, 1, 0.283]}
      />
      <mesh
        geometry={nodes.Poster3.geometry}
        material={nodes.Poster3.material}
        position={[2.185, 2.974, -3.089]}
        rotation={[Math.PI / 2, 0.087, 0]}
        scale={[0.2, 1, 0.283]}
      />
      <mesh
        geometry={nodes.Poster4.geometry}
        material={nodes.Poster4.material}
        position={[1.302, 2.362, -3.089]}
        rotation={[Math.PI / 2, 0.087, 0]}
        scale={[0.2, 1, 0.283]}
      />
    </group>
  );
}

useGLTF.preload("/room/NoticeBoard.glb");
